In [1]:
#Домашнее задание №4
#Задача 1
import numpy as np
A=np.array([[1, 2, 1],
           [-2, 1, 1]])
B=np.array([[3, 1],
           [-1, 0],
           [2, 4]])
C=np.array([[-2, 2],
           [1, -1],
           [1, 2]])
Sum_matrix = A.transpose() + 2*B
Sum_matrix1 = B + 2*C
print(Sum_matrix)
print(Sum_matrix1)

[[7 0]
 [0 1]
 [5 9]]
[[-1  5]
 [ 1 -2]
 [ 4  8]]


In [2]:
#Задача 2
import numpy as np
matrix = np.zeros((8,8), dtype=int)
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1
# выводим результат
print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [3]:
import numpy as np
matrix = np.zeros((8,8), dtype=int)
matrix[1::2,::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [4]:
#Задача 3
import numpy as np

# создаем первый вектор
vec1 = np.arange(0, 1.5, 0.1)

# создаем второй вектор
vec2 = np.arange(1, 7)

# преобразуем первый вектор в матрицу 5x3
matr1 = vec1.reshape((5, 3))

# преобразуем второй вектор в матрицу 3x2
matr2 = vec2.reshape((3, 2))

# перемножаем матрицы
result = np.dot(matr1, matr2)

# выводим матрицы и результат перемножения на экран
print("Матрица 1:\n", matr1)
print("Матрица 2:\n", matr2)
print("Результат перемножения:\n", result)

Матрица 1:
 [[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
Матрица 2:
 [[1 2]
 [3 4]
 [5 6]]
Результат перемножения:
 [[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


In [5]:
#Задача 4
import numpy as np

# создаем вектор
vec = np.arange(1, 72, 2, dtype=np.int32)

# выводим исходный вектор на экран
print("Исходный вектор:\n", vec)

# выделяем элементы, кратные 3
vec_3 = vec[vec % 3 == 0]

# выводим вектор с кратными числами на экран
print("Вектор с кратными числами:\n", vec_3)

Исходный вектор:
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]
Вектор с кратными числами:
 [ 3  9 15 21 27 33 39 45 51 57 63 69]
